insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - White, Schroder And Schyl', 837.08, 2, 16, 3, 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee - Irish Cream', 614.88, 2, 156, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Roll, Italian', 666.69, 1, 250, 3, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Pine Nuts, Whole', 550.28, 2, 141, 2, 'ut mauris eget massa tempor convallis nulla neque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tamarind Paste', 356.28, 2, 32, 2, 'sapien cum sociis natoque penatibus et magnis dis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Spice - Montreal Steak Spice', 641.75, 1, 137, 2, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Gherkin', 914.14, 2, 83, 1, 'ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Veal - Loin', 282.42, 4, 131, 2, 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Blouse / Shirt / Sweater', 388.95, 3, 189, 3, 'maecenas leo odio condimentum id luctus nec molestie sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - Prawn', 912.24, 3, 142, 3, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Loaf Pan - 2 Lb, Foil', 195.12, 3, 100, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Passion Fruit', 155.57, 3, 45, 3, 'sit amet cursus id turpis integer aliquet massa');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cod - Salted, Boneless', 795.73, 2, 14, 2, 'nam dui proin leo odio porttitor id consequat in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salt - Rock, Course', 649.87, 3, 145, 3, 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Rosee', 990.71, 1, 62, 1, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - 16/20, Iqf, Shell On', 217.0, 3, 115, 2, 'sodales scelerisque mauris sit amet eros suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - 10 Grain Parisian', 954.2, 1, 227, 3, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Red, Mosaic Zweigelt', 371.77, 1, 60, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Glass - Wine, Plastic, Clear 5 Oz', 245.56, 3, 31, 2, 'sapien placerat ante nulla justo aliquam quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Trout - Rainbow, Fresh', 672.98, 4, 130, 1, 'vel sem sed sagittis nam congue risus semper porta volutpat quam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tea - Herbal Sweet Dreams', 220.42, 4, 196, 3, 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Salsa', 615.0, 2, 162, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wood Chips - Regular', 710.81, 2, 166, 3, 'platea dictumst maecenas ut massa quis augue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mop Head - Cotton, 24 Oz', 514.4, 2, 40, 2, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scallops 60/80 Iqf', 360.78, 3, 105, 2, 'dis parturient montes nascetur ridiculus mus etiam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells, Chix Gumbo', 968.94, 3, 140, 2, 'convallis nunc proin at turpis a');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tart Shells - Sweet, 4', 858.94, 4, 37, 3, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Gatorade - Fruit Punch', 688.03, 3, 102, 1, 'nulla quisque arcu libero rutrum ac lobortis vel');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Red Pepper Paste', 131.59, 3, 59, 2, 'justo etiam pretium iaculis justo in hac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Napkin White', 429.15, 3, 162, 2, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lentils - Green, Dry', 954.09, 4, 53, 3, 'aliquet maecenas leo odio condimentum id luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mustard - Individual Pkg', 609.46, 1, 178, 2, 'justo maecenas rhoncus aliquam lacus morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Back, Long Cut, Boneless', 313.79, 1, 190, 2, 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tea - Earl Grey', 155.67, 3, 178, 2, 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Loin, Boneless', 421.61, 2, 164, 3, 'penatibus et magnis dis parturient montes');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oil - Canola', 554.55, 2, 159, 3, 'non mattis pulvinar nulla pede ullamcorper augue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - 100 / 200 Cold Water', 541.35, 1, 108, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cut Wakame - Hanawakaba', 312.79, 1, 93, 1, 'rhoncus sed vestibulum sit amet cursus id turpis integer');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - 150 - 250', 342.88, 4, 150, 3, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Zinfandel California 2002', 650.58, 4, 64, 3, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bar Bran Honey Nut', 895.3, 3, 203, 3, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Curry Paste - Madras', 290.88, 1, 75, 1, 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Roe - Flying Fish', 785.42, 4, 212, 2, 'potenti nullam porttitor lacus at turpis donec posuere');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crackers - Graham', 724.92, 4, 10, 3, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Black, Crushed', 165.41, 3, 109, 1, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Red, Lurton Merlot De', 705.13, 3, 175, 1, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tia Maria', 666.8, 4, 146, 2, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Tenderloin', 229.38, 3, 232, 2, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Plasticforkblack', 536.6, 1, 227, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lamb - Pieces, Diced', 438.33, 1, 172, 1, 'odio porttitor id consequat in consequat ut nulla sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Chop, Frenched', 187.77, 3, 228, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Gewurztraminer Pierre', 519.43, 4, 137, 3, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Kahlua', 155.25, 1, 233, 2, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Smoked Tongue', 415.43, 4, 234, 3, 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Seabream Whole Farmed', 318.87, 1, 118, 1, 'magna bibendum imperdiet nullam orci pede venenatis non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flower - Commercial Spider', 715.82, 4, 14, 2, 'nam ultrices libero non mattis pulvinar nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Rosso Del Veronese Igt', 387.82, 4, 162, 1, 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Olive - Spread Tapenade', 202.32, 2, 177, 1, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lid Coffee Cup 8oz Blk', 394.3, 2, 219, 1, 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cake Circle, Paprus', 522.1, 2, 247, 2, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lobak', 125.17, 1, 42, 3, 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Galliano', 181.58, 2, 172, 1, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flower - Leather Leaf Fern', 805.18, 2, 234, 2, 'ante vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oregano - Fresh', 213.52, 3, 43, 3, 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Creme De Cacao White', 177.21, 3, 247, 3, 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bar Special K', 142.13, 4, 16, 1, 'at velit eu est congue elementum in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flour - Buckwheat, Dark', 506.85, 1, 173, 3, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Walkers Special Old Whiskey', 555.28, 3, 80, 1, 'eleifend pede libero quis orci nullam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salmon - Smoked, Sliced', 202.52, 2, 69, 3, 'ante ipsum primis in faucibus orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Olives - Nicoise', 233.1, 4, 169, 3, 'id massa id nisl venenatis lacinia aenean sit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sprouts - Peppercress', 258.81, 2, 236, 3, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Casillero Deldiablo', 319.73, 1, 204, 2, 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Table Cloth - 53x69 Colour', 919.47, 3, 160, 3, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beans - Kidney, Canned', 993.07, 1, 157, 1, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Ruffino Chianti', 634.92, 3, 82, 3, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Clams - Canned', 454.61, 4, 137, 3, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Fish - Atlantic Salmon, Cold', 530.41, 2, 194, 3, 'convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Niagara,vqa Reisling', 180.97, 4, 182, 3, 'orci vehicula condimentum curabitur in libero');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper Squash', 897.51, 4, 69, 3, 'ante vel ipsum praesent blandit lacinia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Pain Au Liat X12', 931.64, 1, 182, 1, 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Creme De Banane - Marie', 131.63, 4, 52, 1, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Rambutan', 925.05, 2, 102, 1, 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('The Pop Shoppe Pinapple', 725.86, 4, 10, 3, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oil - Olive', 368.42, 4, 72, 2, 'orci vehicula condimentum curabitur in libero');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lemon Tarts', 867.68, 1, 178, 1, 'vel pede morbi porttitor lorem id');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Carbonated Water - Strawberry', 139.75, 1, 78, 3, 'sagittis nam congue risus semper porta volutpat quam pede');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Marinara', 133.65, 4, 194, 2, 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tuna - Canned, Flaked, Light', 594.63, 3, 240, 3, 'lorem vitae mattis nibh ligula nec sem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - Tiger 21/25', 560.5, 2, 41, 3, 'volutpat convallis morbi odio odio elementum eu interdum eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Leeks - Large', 168.17, 2, 80, 2, 'ornare imperdiet sapien urna pretium nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Lou Black Shiraz', 710.16, 1, 150, 2, 'vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - Cubes', 853.54, 2, 185, 1, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - Leg, Fresh', 645.63, 2, 71, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scallops - 20/30', 997.5, 2, 143, 3, 'sed augue aliquam erat volutpat in congue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Knorr, Classic Can. Chili', 804.69, 4, 114, 1, 'morbi odio odio elementum eu interdum eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chocolate Bar - Coffee Crisp', 583.58, 1, 105, 3, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salad Dressing', 705.8, 3, 224, 3, 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Anchovy Paste - 56 G Tube', 970.01, 4, 78, 3, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Versatainer Nc - 9388', 781.51, 4, 189, 1, 'proin risus praesent lectus vestibulum quam sapien varius');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Brie,danish', 532.72, 2, 91, 3, 'sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lamb Leg - Bone - In Nz', 800.97, 4, 213, 1, 'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sage - Ground', 265.43, 4, 116, 1, 'rutrum nulla tellus in sagittis dui vel');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pastry - Cheese Baked Scones', 104.73, 3, 146, 2, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beans - Green', 874.52, 1, 74, 2, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee Guatemala Dark', 663.25, 3, 59, 3, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chips - Potato Jalapeno', 139.79, 2, 121, 2, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatillo', 320.25, 3, 94, 1, 'augue aliquam erat volutpat in congue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Magnotta, Merlot Sr Vqa', 411.77, 1, 190, 1, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Filling - Mince Meat', 681.54, 1, 244, 3, 'quis libero nullam sit amet turpis elementum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Milk 2% 500 Ml', 324.47, 2, 164, 2, 'consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Table Cloth 54x54 Colour', 198.16, 4, 98, 2, 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - White Epi Baguette', 488.09, 4, 54, 2, 'at nulla suspendisse potenti cras in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vinegar - White', 435.65, 4, 250, 3, 'donec semper sapien a libero nam dui proin');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Monkfish Fresh - Skin Off', 115.34, 4, 195, 2, 'nam dui proin leo odio porttitor id consequat in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Barley - Pearl', 196.77, 4, 16, 3, 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Red Currants', 854.89, 2, 198, 1, 'at turpis a pede posuere nonummy integer');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - Crumb', 747.06, 3, 25, 2, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Syrup - Monin, Irish Cream', 622.58, 4, 205, 3, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Carbonated Water - Raspberry', 498.13, 2, 25, 2, 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chocolate - Feathers', 474.2, 1, 110, 1, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Canada Dry', 491.84, 4, 146, 3, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - Whole Roasting', 786.67, 3, 178, 1, 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Steampan - Lid For Half Size', 766.72, 4, 25, 2, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - Diced, Cooked', 695.45, 3, 38, 1, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Instant Coffee', 814.64, 2, 167, 3, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bamboo Shoots - Sliced', 445.02, 3, 16, 2, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Heavy Duty Dust Pan', 692.96, 3, 184, 1, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lettuce - Frisee', 821.0, 1, 147, 2, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Leeks - Large', 627.34, 3, 220, 2, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tia Maria', 419.77, 2, 141, 1, 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Onions - Dried, Chopped', 108.54, 2, 112, 2, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Cheddarsliced', 177.31, 4, 204, 2, 'ipsum primis in faucibus orci luctus et ultrices');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffin Mix - Banana Nut', 363.98, 1, 186, 3, 'mi integer ac neque duis bibendum morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Steampan Lid', 696.95, 1, 58, 2, 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Turnip - White, Organic', 762.16, 2, 154, 1, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - White, Chardonnay', 877.27, 1, 17, 2, 'auctor sed tristique in tempus sit amet sem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Victor Et Berthold', 768.05, 3, 37, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Artichokes - Jerusalem', 842.76, 2, 170, 2, 'amet sem fusce consequat nulla nisl nunc nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sage Derby', 970.83, 2, 77, 3, 'consequat lectus in est risus auctor sed tristique in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Sour Sticks With Onion', 463.12, 3, 178, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Guava', 336.33, 3, 191, 1, 'mauris viverra diam vitae quam suspendisse potenti');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Rosemary - Primerba, Paste', 962.68, 3, 25, 1, 'feugiat non pretium quis lectus suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Versatainer Nc - 9388', 149.96, 3, 181, 3, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - White Packet', 238.89, 3, 18, 1, 'ac diam cras pellentesque volutpat dui maecenas tristique est');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Potatoes - Pei 10 Oz', 995.17, 4, 142, 2, 'in quis justo maecenas rhoncus aliquam lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crab - Dungeness, Whole, live', 449.14, 2, 141, 3, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chips Potato All Dressed - 43g', 886.88, 4, 153, 3, 'vel sem sed sagittis nam congue risus semper porta');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yogurt - French Vanilla', 816.24, 1, 75, 1, 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Fish - Bones', 417.94, 1, 156, 1, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffins - Assorted', 758.36, 2, 241, 2, 'sollicitudin vitae consectetuer eget rutrum at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - Palm', 184.79, 2, 227, 1, 'duis ac nibh fusce lacus purus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Red Snapper - Fresh, Whole', 957.6, 1, 152, 1, 'a ipsum integer a nibh in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Filter - Coffee', 888.18, 2, 38, 3, 'tristique est et tempus semper est quam pharetra magna ac consequat metus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vector Energy Bar', 506.5, 4, 191, 2, 'sapien ut nunc vestibulum ante ipsum primis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Plums - Red', 935.04, 3, 85, 1, 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Island Oasis - Wildberry', 514.17, 2, 25, 2, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Container - Clear 16 Oz', 323.59, 2, 144, 1, 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Milk 2% 500 Ml', 526.07, 4, 232, 1, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Red Thai', 736.91, 2, 66, 1, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pizza Pizza Dough', 890.11, 3, 180, 1, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Jalapeno', 155.83, 3, 246, 1, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Thyme - Fresh', 490.23, 2, 17, 3, 'nascetur ridiculus mus etiam vel augue vestibulum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Penne, Lisce, Dry', 207.78, 4, 102, 1, 'eu sapien cursus vestibulum proin eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oil - Sunflower', 785.09, 2, 70, 3, 'in faucibus orci luctus et ultrices posuere cubilia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Parasol Pick Stir Stick', 227.06, 4, 131, 1, 'justo morbi ut odio cras mi pede malesuada');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Bernaise, Mix', 769.94, 4, 61, 1, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pear - Halves', 971.07, 1, 105, 3, 'eget tincidunt eget tempus vel pede morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cocoa Powder - Natural', 990.11, 3, 159, 3, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crab - Claws, Snow 16 - 24', 286.57, 1, 216, 1, 'duis bibendum felis sed interdum venenatis turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Masi Valpolocell', 747.53, 3, 84, 3, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Tender Tips', 549.43, 3, 104, 2, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cup - 3.5oz, Foam', 746.23, 3, 84, 1, 'odio consequat varius integer ac leo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wakami Seaweed', 379.23, 1, 22, 3, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Barolo Fontanafredda', 447.56, 3, 223, 2, 'eleifend pede libero quis orci nullam molestie');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Syrup - Monin, Amaretta', 227.92, 3, 115, 1, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Graham Cracker Mix', 811.09, 2, 157, 1, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Magnotta, Merlot Sr Vqa', 106.23, 1, 184, 3, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lid Tray - 16in Dome', 863.62, 3, 193, 3, 'viverra dapibus nulla suscipit ligula in lacus curabitur at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Rioja Campo Viejo', 315.89, 4, 161, 3, 'nisl aenean lectus pellentesque eget nunc donec quis orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chips Potato All Dressed - 43g', 460.47, 2, 131, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pie Filling - Pumpkin', 641.27, 2, 232, 3, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Rice - Long Grain', 643.65, 4, 112, 3, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Walnut, Pieces', 722.2, 3, 231, 2, 'nec dui luctus rutrum nulla tellus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Mint', 170.72, 1, 237, 3, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yokaline', 437.46, 3, 62, 2, 'praesent id massa id nisl venenatis lacinia aenean');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cassis', 919.64, 1, 86, 2, 'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Eye Of Round', 737.93, 2, 30, 3, 'viverra diam vitae quam suspendisse potenti nullam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Trout - Rainbow, Fresh', 186.16, 1, 169, 1, 'vel accumsan tellus nisi eu orci mauris');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Steampan - Lid For Half Size', 926.21, 2, 171, 1, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bowl 12 Oz - Showcase 92012', 664.03, 2, 53, 1, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mushroom - Oyster, Fresh', 919.29, 1, 114, 3, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Dried Cranberries', 210.18, 3, 113, 2, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Sicilia Igt Nero Avola', 898.1, 1, 55, 3, 'augue vestibulum rutrum rutrum neque aenean auctor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lamb - Shoulder, Boneless', 157.63, 4, 71, 2, 'augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('General Purpose Trigger', 638.83, 2, 161, 3, 'nulla mollis molestie lorem quisque ut erat curabitur');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Five Alive Citrus', 268.54, 1, 196, 2, 'accumsan odio curabitur convallis duis consequat dui nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Island Oasis - Ice Cream Mix', 916.68, 3, 212, 1, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Pablano', 468.43, 3, 151, 1, 'blandit nam nulla integer pede justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Red Currant Jelly', 498.41, 1, 80, 3, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Orzo, Dry', 682.27, 1, 52, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Saskatoon Berries - Frozen', 100.49, 2, 197, 3, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mussels - Cultivated', 110.29, 3, 184, 3, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flour - Pastry', 175.07, 1, 96, 3, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - White Meat With Tender', 560.63, 4, 202, 2, 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lamb - Sausage Casings', 937.38, 2, 71, 3, 'sapien a libero nam dui proin leo odio porttitor id consequat in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Potatoes - Mini White 3 Oz', 231.24, 3, 110, 2, 'odio in hac habitasse platea dictumst maecenas');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oil - Olive', 849.33, 4, 111, 1, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Fireball Whisky', 132.45, 3, 72, 3, 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Fusili, Dry', 612.7, 2, 181, 3, 'quis augue luctus tincidunt nulla mollis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Celery', 447.78, 1, 100, 3, 'penatibus et magnis dis parturient montes');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cinnamon - Stick', 993.52, 3, 185, 3, 'semper est quam pharetra magna ac consequat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - White, Mosel Gold', 973.87, 4, 234, 3, 'pretium iaculis diam erat fermentum justo nec condimentum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Appetizer - Asian Shrimp Roll', 241.34, 4, 167, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chocolate Bar - Oh Henry', 568.4, 3, 23, 1, 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yeast Dry - Fleischman', 667.32, 1, 121, 1, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ham - Virginia', 196.69, 1, 237, 1, 'in felis eu sapien cursus vestibulum proin eu mi nulla ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Island Oasis - Peach Daiquiri', 143.93, 4, 61, 1, 'vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - Wings, Tip Off', 429.41, 1, 100, 3, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Almond, Blanched, Whole', 676.21, 3, 181, 2, 'diam vitae quam suspendisse potenti nullam porttitor lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lid - 10,12,16 Oz', 609.03, 2, 140, 1, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Barolo Fontanafredda', 336.21, 1, 247, 1, 'accumsan felis ut at dolor quis odio consequat varius integer ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ecolab - Orange Frc, Cleaner', 925.18, 3, 131, 3, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Red, Mosaic Zweigelt', 275.83, 3, 198, 1, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cup - 4oz Translucent', 847.34, 1, 181, 1, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - 100 / 200 Cold Water', 919.51, 2, 174, 1, 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells, Minestrone', 485.49, 4, 113, 2, 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sobe - Lizard Fuel', 846.33, 2, 239, 1, 'nibh in hac habitasse platea dictumst');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Steel Wool', 378.89, 3, 166, 1, 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Iced Tea - Lemon, 340ml', 215.66, 2, 220, 2, 'massa volutpat convallis morbi odio odio elementum eu interdum eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread Crumbs - Japanese Style', 487.55, 4, 67, 2, 'risus auctor sed tristique in tempus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Table Cloth 62x120 White', 236.78, 3, 29, 1, 'morbi non quam nec dui luctus rutrum nulla tellus in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lemons', 888.84, 4, 35, 1, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Ej Gallo Sonoma', 868.97, 2, 97, 1, 'mattis pulvinar nulla pede ullamcorper augue a');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Prime Rib Aaa', 157.54, 1, 41, 3, 'eros viverra eget congue eget semper rutrum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Sticks, Thin, Plain', 970.06, 2, 118, 3, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Steel Wool', 209.04, 3, 58, 3, 'in lectus pellentesque at nulla suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Jolt Cola - Electric Blue', 734.59, 4, 213, 3, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tea - Green', 188.92, 1, 27, 3, 'cursus id turpis integer aliquet massa id lobortis convallis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Champagne - Brights, Dry', 768.41, 3, 135, 2, 'sed ante vivamus tortor duis mattis egestas metus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee - Colombian, Portioned', 322.5, 1, 25, 3, 'felis ut at dolor quis odio consequat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chocolate - Feathers', 358.06, 3, 58, 3, 'odio curabitur convallis duis consequat dui nec nisi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Quail - Jumbo', 554.77, 2, 249, 1, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Corn Muffaleta Onion', 192.95, 2, 119, 2, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Onions - Spanish', 808.98, 4, 20, 2, 'lectus vestibulum quam sapien varius ut blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coconut - Creamed, Pure', 421.24, 4, 139, 1, 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lobster - Baby, Boiled', 401.17, 1, 91, 3, 'ante ipsum primis in faucibus orci luctus et ultrices');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scallops - Live In Shell', 195.9, 4, 247, 3, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Breakfast Quesadillas', 566.5, 2, 98, 3, 'ut nunc vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crab - Blue, Frozen', 451.07, 4, 223, 1, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Two Oceans Cabernet', 635.9, 3, 55, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Chillies, Crushed', 464.48, 1, 103, 1, 'faucibus orci luctus et ultrices posuere cubilia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Fett Alfredo, Single Serve', 391.96, 2, 239, 3, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffin Mix - Lemon Cranberry', 792.46, 3, 143, 1, 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Brandy - Orange, Mc Guiness', 166.08, 1, 50, 3, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Pumpernickel', 212.12, 1, 221, 1, 'sapien placerat ante nulla justo aliquam quis turpis eget elit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salmon - Atlantic, No Skin', 646.22, 1, 46, 2, 'imperdiet et commodo vulputate justo in blandit ultrices');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Propel Sport Drink', 129.8, 1, 197, 1, 'accumsan felis ut at dolor quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oil - Olive', 924.62, 4, 41, 2, 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tea - Herbal - 6 Asst', 230.32, 2, 153, 3, 'massa quis augue luctus tincidunt nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Gnocchi, Potato', 356.43, 3, 102, 2, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Apple - Fuji', 215.37, 3, 136, 2, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Olive Dinner Roll', 557.27, 4, 64, 2, 'mauris eget massa tempor convallis nulla neque libero');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Rhubarb', 934.07, 2, 185, 1, 'sapien varius ut blandit non interdum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ice Cream - Turtles Stick Bar', 638.41, 4, 211, 2, 'nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Magnotta - Belpaese', 740.92, 3, 24, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lotus Root', 261.14, 4, 205, 3, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Whmis - Spray Bottle Trigger', 536.32, 1, 233, 3, 'quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Turkey - Breast, Smoked', 623.57, 3, 115, 2, 'interdum in ante vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cookie Double Choco', 552.85, 4, 75, 3, 'lacinia sapien quis libero nullam sit amet turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells Asian Noodle', 875.3, 2, 202, 3, 'ultrices phasellus id sapien in sapien iaculis congue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tortillas - Flour, 12', 662.65, 2, 143, 1, 'eleifend pede libero quis orci nullam molestie nibh');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Puff Pastry - Sheets', 502.69, 1, 238, 1, 'est congue elementum in hac habitasse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Squid - Tubes / Tenticles 10/20', 966.34, 4, 54, 2, 'nulla ut erat id mauris vulputate');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes Tear Drop', 913.99, 2, 82, 1, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Dried Cherries', 830.44, 1, 245, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Mini Hamburger Bun', 773.96, 3, 155, 2, 'tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pesto - Primerba, Paste', 107.16, 3, 165, 3, 'quis odio consequat varius integer ac leo pellentesque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ecolab - Hobart Upr Prewash Arm', 860.45, 4, 182, 1, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread Base - Italian', 382.09, 3, 148, 1, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oven Mitts 17 Inch', 702.98, 4, 54, 2, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Tenderloin, Fresh', 451.78, 4, 120, 2, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Onions - Dried, Chopped', 146.16, 1, 138, 2, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beer - Original Organic Lager', 402.35, 2, 225, 1, 'ut rhoncus aliquet pulvinar sed nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Melon - Watermelon Yellow', 490.31, 3, 199, 1, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chips Potato Swt Chilli Sour', 189.39, 1, 40, 1, 'bibendum felis sed interdum venenatis turpis enim blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Appetizer - Tarragon Chicken', 897.57, 1, 79, 3, 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Kale - Red', 437.38, 1, 112, 1, 'imperdiet et commodo vulputate justo in blandit ultrices');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - English Muffin', 744.75, 1, 231, 2, 'nullam varius nulla facilisi cras non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Transfer Sheets', 263.51, 1, 32, 2, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Halibut - Whole, Fresh', 197.79, 1, 164, 1, 'tempor convallis nulla neque libero convallis eget eleifend');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Juice - Clam, 46 Oz', 266.4, 4, 150, 1, 'suscipit a feugiat et eros vestibulum ac est lacinia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce - Mint', 223.6, 3, 165, 2, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee Cup 16oz Foam', 862.31, 2, 145, 2, 'felis ut at dolor quis odio consequat varius');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tea - Herbal Orange Spice', 982.82, 1, 36, 1, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Vouvray Cuvee Domaine', 675.59, 4, 179, 2, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('7up Diet, 355 Ml', 350.11, 2, 51, 2, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Higashimaru Usukuchi Soy', 229.08, 2, 146, 3, 'augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken - Leg, Fresh', 379.11, 1, 148, 3, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Puligny Montrachet A.', 395.78, 2, 129, 3, 'dolor quis odio consequat varius integer');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Mozzarella', 554.92, 4, 56, 2, 'sed nisl nunc rhoncus dui vel');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pan Grease', 313.15, 3, 196, 2, 'lectus pellentesque eget nunc donec quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pumpkin - Seed', 944.33, 4, 117, 2, 'lectus in quam fringilla rhoncus mauris enim');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup Knorr Chili With Beans', 819.48, 3, 77, 2, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Water - Spring Water, 355 Ml', 516.11, 3, 17, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flour - Whole Wheat', 524.63, 1, 22, 3, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Angel Hair', 527.84, 4, 132, 2, 'lectus in est risus auctor sed tristique in tempus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crab - Claws, Snow 16 - 24', 762.59, 4, 24, 2, 'amet eleifend pede libero quis orci nullam molestie nibh in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Hagen Daza - Dk Choocolate', 500.33, 1, 20, 3, 'est congue elementum in hac habitasse platea');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sambuca - Opal Nera', 876.74, 2, 34, 2, 'suspendisse potenti nullam porttitor lacus at turpis donec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Trout - Smoked', 309.76, 2, 208, 1, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scotch - Queen Anne', 434.44, 3, 57, 3, 'faucibus cursus urna ut tellus nulla ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Filo Dough', 990.91, 1, 48, 3, 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beer - Tetleys', 327.6, 1, 158, 1, 'rhoncus mauris enim leo rhoncus sed vestibulum sit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Appetizer - Cheese Bites', 461.28, 3, 21, 1, 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Valpolicella Masi', 288.75, 3, 103, 1, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Milk - Buttermilk', 744.88, 2, 179, 1, 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - La Sauvagine', 141.14, 1, 178, 2, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Potatoes - Idaho 80 Count', 760.23, 2, 167, 1, 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Peanut, Roasted', 821.42, 2, 28, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bacardi Limon', 118.1, 3, 160, 3, 'consequat morbi a ipsum integer a nibh in quis justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee - Cafe Moreno', 627.01, 3, 214, 3, 'arcu adipiscing molestie hendrerit at vulputate');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Vovray Sec Domaine Huet', 755.92, 2, 236, 3, 'donec dapibus duis at velit eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Placido Pinot Grigo', 559.23, 2, 144, 1, 'nulla sed vel enim sit amet nunc viverra dapibus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Juice - Apple, 341 Ml', 179.45, 2, 82, 3, 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Cayenne', 847.46, 4, 189, 3, 'proin leo odio porttitor id consequat in consequat ut nulla sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Triangle White', 279.29, 2, 209, 1, 'porttitor id consequat in consequat ut nulla sed accumsan');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Versatainer Nc - 888', 436.95, 1, 104, 1, 'ante ipsum primis in faucibus orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes - Cherry', 549.51, 4, 196, 2, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Food Colouring - Orange', 118.07, 3, 69, 1, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Extract - Lemon', 830.11, 3, 31, 1, 'pede justo eu massa donec dapibus duis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lettuce - Romaine, Heart', 657.33, 3, 120, 2, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Charddonnay Errazuriz', 318.33, 4, 64, 2, 'sit amet cursus id turpis integer aliquet massa id');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Red Currant Jelly', 725.93, 4, 65, 3, 'felis ut at dolor quis odio consequat varius integer');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('True - Vue Containers', 777.83, 2, 80, 1, 'lectus vestibulum quam sapien varius ut blandit non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Juice - Clam, 46 Oz', 412.95, 3, 36, 2, 'vehicula condimentum curabitur in libero ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('External Supplier', 794.97, 3, 19, 2, 'nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Poppy Seed', 503.2, 3, 52, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells Pasta Fagioli', 266.61, 3, 130, 3, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Asparagus - Mexican', 555.68, 4, 37, 3, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Thyme - Dried', 453.39, 4, 247, 2, 'in magna bibendum imperdiet nullam orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Hummus - Spread', 772.38, 3, 248, 2, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffin Mix - Chocolate Chip', 513.88, 3, 231, 1, 'augue vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Dragon Fruit', 504.25, 4, 162, 1, 'vestibulum rutrum rutrum neque aenean auctor gravida');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pears - Anjou', 572.74, 4, 150, 1, 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Snapple - Iced Tea Peach', 921.52, 2, 228, 3, 'turpis eget elit sodales scelerisque mauris');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Soave Folonari', 158.53, 3, 26, 3, 'morbi a ipsum integer a nibh in quis justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes - Vine Ripe, Yellow', 904.14, 1, 99, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pepper - Black, Whole', 312.47, 2, 145, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cookie - Oreo 100x2', 562.4, 3, 205, 1, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lettuce - Red Leaf', 183.82, 1, 124, 1, 'ut mauris eget massa tempor convallis nulla neque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sambuca Cream', 992.68, 3, 193, 2, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vanilla Beans', 752.09, 4, 136, 3, 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Peach - Halves', 673.02, 1, 209, 1, 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Magnotta - Red, Baco', 376.69, 2, 168, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beer - Steamwhistle', 382.05, 3, 23, 1, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Blue', 257.75, 1, 227, 2, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Puree - Blackcurrant', 778.86, 1, 223, 2, 'quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cake - Pancake', 296.22, 2, 234, 1, 'convallis nulla neque libero convallis eget eleifend luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Spinach - Packaged', 777.63, 4, 136, 1, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes', 543.42, 1, 189, 1, 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vodka - Lemon, Absolut', 656.85, 3, 109, 2, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salad Dressing', 723.18, 4, 152, 1, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Langers - Cranberry Cocktail', 907.91, 1, 225, 2, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lidsoupcont Rp12dn', 424.88, 2, 182, 2, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes - Cherry, Yellow', 371.14, 1, 207, 3, 'sapien quis libero nullam sit amet turpis elementum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - Baby, Cold Water', 662.17, 1, 206, 1, 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vinegar - Tarragon', 971.14, 1, 54, 3, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bar Nature Valley', 558.98, 1, 197, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bok Choy - Baby', 182.33, 1, 135, 3, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Creme De Cacao White', 234.38, 4, 85, 3, 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Garlic - Elephant', 324.98, 4, 41, 2, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Blueberries - Frozen', 833.78, 4, 231, 2, 'bibendum felis sed interdum venenatis turpis enim blandit mi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sandwich Wrap', 741.68, 2, 185, 2, 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ezy Change Mophandle', 968.77, 2, 227, 3, 'suspendisse potenti nullam porttitor lacus at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Fenngreek Seed', 562.19, 1, 199, 1, 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Pine Nuts, Whole', 423.95, 3, 70, 2, 'tellus semper interdum mauris ullamcorper purus sit amet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Triangle White', 846.45, 2, 224, 3, 'felis sed interdum venenatis turpis enim blandit mi in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cup - 8oz Coffee Perforated', 363.58, 4, 35, 1, 'ullamcorper augue a suscipit nulla elit ac nulla sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bagelers - Cinn / Brown Sugar', 902.88, 4, 100, 3, 'eros elementum pellentesque quisque porta volutpat erat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffin Hinge Container 6', 284.95, 4, 187, 2, 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lemonade - Island Tea, 591 Ml', 408.34, 2, 197, 2, 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Icecream - Dstk Strw Chseck', 209.56, 4, 239, 2, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sauce Tomato Pouch', 101.68, 3, 59, 2, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sterno - Chafing Dish Fuel', 308.09, 1, 30, 2, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Apricots Fresh', 271.96, 3, 77, 2, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bag Stand', 800.08, 3, 238, 1, 'sed ante vivamus tortor duis mattis egestas metus aenean');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Almond, Blanched, Ground', 344.2, 1, 143, 3, 'curae mauris viverra diam vitae quam suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Lamancha Do Crianza', 991.19, 2, 48, 3, 'condimentum curabitur in libero ut massa volutpat convallis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Goat', 823.17, 1, 205, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Ciabatta Buns', 312.41, 2, 141, 1, 'pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nantucket - Carrot Orange', 637.32, 2, 239, 1, 'quis justo maecenas rhoncus aliquam lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oregano - Dry, Rubbed', 723.6, 4, 149, 2, 'vel augue vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sea Bass - Fillets', 669.18, 4, 147, 2, 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells Chili', 472.6, 2, 230, 2, 'sollicitudin vitae consectetuer eget rutrum at lorem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Grand Marnier', 195.19, 2, 121, 3, 'nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Spoon - Soup, Plastic', 634.4, 1, 172, 3, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Water - Mineral, Natural', 698.24, 1, 171, 1, 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Browning Caramel Glace', 718.7, 2, 150, 1, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Allspice - Jamaican', 324.38, 1, 68, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread Ww Cluster', 755.75, 1, 242, 3, 'sapien cum sociis natoque penatibus et magnis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('V8 - Berry Blend', 610.72, 4, 175, 1, 'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - White, Riesling, Semi - Dry', 578.5, 2, 210, 2, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chocolate Bar - Smarties', 497.26, 3, 233, 3, 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Pumpkin Seeds', 250.42, 2, 211, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Ice Cream Bar - Oreo Sandwich', 760.27, 1, 207, 3, 'proin interdum mauris non ligula pellentesque ultrices phasellus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mace Ground', 729.1, 3, 245, 1, 'congue risus semper porta volutpat quam pede lobortis ligula');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Glass - Wine, Plastic, Clear 5 Oz', 621.61, 1, 154, 1, 'molestie lorem quisque ut erat curabitur gravida nisi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Spring Roll Wrappers', 861.17, 2, 88, 1, 'egestas metus aenean fermentum donec ut mauris eget massa');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Muffin Mix - Banana Nut', 199.04, 1, 186, 2, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Chuck, Boneless', 520.13, 1, 14, 1, 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pan Grease', 448.77, 2, 234, 3, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Coffee - Hazelnut Cream', 271.17, 1, 139, 3, 'neque sapien placerat ante nulla justo aliquam quis turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Breakfast Quesadillas', 277.37, 2, 152, 3, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sprite, Diet - 355ml', 858.33, 1, 199, 3, 'justo aliquam quis turpis eget elit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Juice - V8, Tomato', 622.84, 2, 49, 3, 'neque sapien placerat ante nulla justo aliquam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Rotini, Dry', 600.51, 4, 212, 1, 'varius ut blandit non interdum in ante vestibulum ante ipsum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Hagen Daza - Dk Choocolate', 673.69, 4, 237, 3, 'et ultrices posuere cubilia curae nulla dapibus dolor');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pie Filling - Apple', 955.63, 3, 208, 2, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bok Choy - Baby', 854.44, 3, 150, 2, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sprouts - Bean', 677.19, 4, 223, 2, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beans - Kidney, Red Dry', 534.21, 4, 123, 3, 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cauliflower', 303.28, 1, 179, 3, 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Grapes - Red', 307.71, 2, 191, 2, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Icecream - Dibs', 472.45, 2, 248, 2, 'urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crackers - Trio', 397.39, 2, 18, 2, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Turkey - Ground. Lean', 183.42, 4, 155, 1, 'sapien non mi integer ac neque duis bibendum morbi non quam nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Squid - Tubes / Tenticles 10/20', 707.83, 1, 32, 1, 'justo pellentesque viverra pede ac diam cras pellentesque');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pastry - Lemon Danish - Mini', 639.43, 2, 140, 1, 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Chicken Thigh - Bone Out', 662.95, 4, 188, 3, 'aenean auctor gravida sem praesent id');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Eggplant - Baby', 682.85, 1, 14, 1, 'lorem ipsum dolor sit amet consectetuer adipiscing');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cake - Miini Cheesecake Cherry', 280.07, 2, 169, 3, 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Energy - Boo - Koo', 532.01, 2, 174, 3, 'mi integer ac neque duis bibendum morbi non quam nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Vinegar - Balsamic, White', 501.64, 3, 34, 2, 'interdum mauris non ligula pellentesque ultrices phasellus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Bistro Sour', 842.7, 1, 110, 1, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Bakers Cream Cheese', 345.2, 1, 46, 1, 'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Chuck, Boneless', 671.78, 3, 152, 3, 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Bagels, Mini', 645.3, 1, 75, 3, 'metus arcu adipiscing molestie hendrerit at');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nut - Pine Nuts, Whole', 133.4, 2, 10, 1, 'tempor convallis nulla neque libero convallis eget eleifend luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Potatoes - Instant, Mashed', 257.73, 2, 200, 1, 'faucibus cursus urna ut tellus nulla ut erat id mauris');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lettuce - Frisee', 179.19, 2, 233, 2, 'magna at nunc commodo placerat praesent blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Plate - Foam, Bread And Butter', 520.97, 2, 58, 3, 'nonummy integer non velit donec diam neque vestibulum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Cahors Ac 2000, Clos', 745.54, 2, 59, 2, 'sem duis aliquam convallis nunc proin at turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Dates', 698.22, 3, 75, 1, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - Brown, Individual', 443.07, 4, 90, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Hock And Feet Attached', 134.13, 1, 73, 3, 'at feugiat non pretium quis lectus suspendisse');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Remy Red Berry Infusion', 374.73, 1, 52, 3, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Gherkin - Sour', 277.57, 1, 55, 2, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Salt - Sea', 704.52, 2, 181, 3, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yogurt - Blueberry, 175 Gr', 642.93, 2, 217, 1, 'augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yokaline', 357.37, 2, 175, 1, 'vehicula condimentum curabitur in libero ut massa volutpat convallis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Jack Daniels', 218.22, 4, 46, 2, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Remy Pannier Rose', 549.65, 3, 131, 1, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scampi Tail', 672.55, 1, 130, 2, 'potenti in eleifend quam a odio in hac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Nantucket Pine Orangebanana', 337.09, 4, 61, 1, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Bacon,back Peameal', 964.5, 1, 152, 2, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mangostein', 902.8, 3, 72, 3, 'tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Shiraz South Eastern', 871.22, 4, 48, 3, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Vineland Estate Semi - Dry', 640.48, 4, 151, 3, 'nec sem duis aliquam convallis nunc proin at turpis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Brandy Apricot', 666.53, 3, 132, 2, 'congue vivamus metus arcu adipiscing molestie');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Juice - Grape, White', 280.16, 4, 77, 1, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yoplait Drink', 939.4, 2, 226, 3, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Lid - 3oz Med Rec', 472.61, 1, 36, 1, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Transfer Sheets', 532.22, 4, 58, 2, 'ornare consequat lectus in est risus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Foam Espresso Cup Plain White', 298.16, 2, 217, 2, 'amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Eggplant Oriental', 267.96, 3, 122, 3, 'erat curabitur gravida nisi at nibh in');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Mcgillicuddy Vanilla Schnap', 119.14, 1, 44, 1, 'ligula nec sem duis aliquam convallis nunc');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Yoghurt Tubes', 758.13, 1, 83, 1, 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Oregano - Dry, Rubbed', 676.65, 1, 92, 2, 'amet turpis elementum ligula vehicula consequat morbi');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Beringer Founders Estate', 755.95, 3, 116, 2, 'at nulla suspendisse potenti cras in purus eu magna');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Tomatoes - Cherry, Yellow', 789.69, 4, 196, 3, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Sugar - Fine', 809.58, 1, 149, 2, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beef - Sushi Flat Iron Steak', 832.36, 4, 27, 3, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('C - Plus, Orange', 952.98, 3, 182, 2, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Extract Vanilla Pure', 357.86, 4, 210, 3, 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Smoked Kassler', 530.15, 2, 132, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pork - Ham, Virginia', 233.43, 4, 16, 1, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Fondant - Icing', 997.86, 1, 43, 1, 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pasta - Fettuccine, Egg, Fresh', 858.43, 2, 114, 1, 'leo odio porttitor id consequat in consequat ut');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells, Lentil', 598.63, 1, 165, 2, 'velit id pretium iaculis diam erat fermentum justo nec');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Schnappes - Peach, Walkers', 683.05, 3, 45, 1, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Milk - 1%', 994.95, 1, 187, 1, 'nibh in quis justo maecenas rhoncus aliquam lacus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Remy Red Berry Infusion', 623.95, 3, 93, 2, 'sed vestibulum sit amet cursus id');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Squash - Butternut', 183.78, 1, 229, 2, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Calaloo', 376.51, 3, 27, 1, 'rutrum nulla nunc purus phasellus in felis donec semper sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup Campbells Beef With Veg', 720.79, 2, 77, 2, null);
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scallops - In Shell', 631.37, 3, 140, 2, 'cubilia curae nulla dapibus dolor vel est donec odio');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Scallops - U - 10', 194.25, 1, 228, 1, 'magna bibendum imperdiet nullam orci pede venenatis');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Soup - Campbells Tomato Ravioli', 124.15, 2, 38, 1, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Fume Blanc Fetzer', 567.46, 4, 41, 3, 'cras pellentesque volutpat dui maecenas tristique est et');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Crab - Meat Combo', 226.38, 4, 204, 1, 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Calypso - Black Cherry Lemonade', 895.53, 1, 23, 3, 'dictumst maecenas ut massa quis augue luctus');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - Tiger 21/25', 647.17, 4, 222, 1, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Beer - True North Lager', 563.71, 3, 218, 2, 'posuere felis sed lacus morbi sem');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Bread - Crumbs, Bulk', 475.63, 3, 13, 3, 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Flour - Cake', 438.14, 1, 60, 2, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Table Cloth 90x90 Colour', 424.82, 3, 202, 2, 'velit vivamus vel nulla eget eros');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Wine - Pinot Noir Latour', 105.17, 2, 10, 2, 'sodales sed tincidunt eu felis fusce posuere felis sed');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Cheese - Goat With Herbs', 571.43, 4, 248, 1, 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Pear - Asian', 844.02, 3, 183, 3, 'nulla ac enim in tempor turpis nec euismod scelerisque quam');
insert into items (name, unit_price, id_category, quantity, id_uom, description) values ('Shrimp - 16 - 20 Cooked, Peeled', 617.52, 2, 51, 1, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
